/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.41).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.eduit.app.springboot.api;

import com.eduit.app.springboot.DTO.CategoryRequestDTO;
import com.eduit.app.springboot.DTO.ProductRequestDTO;
import com.eduit.app.springboot.model.*;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.validation.Valid;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2023-03-21T20:52:22.931324395Z[GMT]")
@Validated
public interface ProductsApi {

    @Operation(summary = "Create product", description = "Create a product, authentication required.", security = {
        @SecurityRequirement(name = "bearerAuth")    }, tags={ "store" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "successful operation", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ResponseContainerProductResponseDTO.class))),
        
        @ApiResponse(responseCode = "401", description = "Access token is missing or invalid") })
    @RequestMapping(value = "/products/product",
        produces = { "application/json" }, 
        consumes = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<ResponseContainerProductResponseDTO> createProduct(@Parameter(in = ParameterIn.DEFAULT, description = "Created product object", schema=@Schema()) @Valid @RequestBody ProductDTO body);


    @Operation(summary = "Retrieve a list of products", description = "Retrieve a list of products, authentication required.", security = {
        @SecurityRequirement(name = "bearerAuth")    }, tags={ "store" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "successful operation", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ProductListDTO.class))) })
    @RequestMapping(value = "/products/product",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<ResponseContainerResponseDTO> retrieveAllProducts();

    ResponseEntity<ResponseContainerResponseDTO> createProduct(ProductRequestDTO productDTO);

    ResponseEntity<ResponseContainerResponseDTO> deleteProduct(Long productId);

    ResponseEntity<ResponseContainerResponseDTO> retrieveProduct(Long productId);

    ResponseEntity<ResponseContainerResponseDTO> updateProduct(Long productId, ProductDTO productDTO);

    ResponseEntity<ResponseContainerResponseDTO> createCategory(CategoryRequestDTO categoryRequestDTO);

    ResponseEntity<ResponseContainerResponseDTO> deleteCategory(Long categoryId);

    ResponseEntity<ResponseContainerResponseDTO> retrieveAllCategory();

    ResponseEntity<ResponseContainerResponseDTO> retrieveCategory(Long categoryId);

    ResponseEntity<ResponseContainerResponseDTO> updateCategory(Long categoryId, CategoryDTO categoryDTO);
}

